<?php
	require_once("system-db.php");
	
	start_db();
	
	function alter($sql) {
		$result = mysql_query($sql);
		
		if (! $result) {
			logError(mysql_error());
		}
	}
	
//	alter("ALTER TABLE africatranscriptions_applicationactionroles ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_applicationactions ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_applicationtablecolumns ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_applicationtables ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_casedocs ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_cases ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_caseterms ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_casetypist ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_casetypistdocs ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_casetypistsessions ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_contacts ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_courts ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_documents ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_errors ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_filter ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alter("ALTER TABLE africatranscriptions_filterdata ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
//	alert("CREATE TABLE africatranscriptions_images (	id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,	path CHAR(255) NULL DEFAULT '',	mimetype CHAR(50) NULL DEFAULT '',	name CHAR(255) NULL DEFAULT '',	imgwidth SMALLINT(4) NULL DEFAULT '0',	imgheight SMALLINT(4) NULL DEFAULT '0',	tag CHAR(255) NULL DEFAULT '',	description CHAR(255) NULL DEFAULT '',	image LONGBLOB NULL,	createddate TIMESTAMP NULL DEFAULT NULL,	metacreateddate DATETIME NOT NULL,	metacreateduserid INT(11) NOT NULL,	metamodifieddate DATETIME NOT NULL,	metamodifieduserid INT(11) NOT NULL,	PRIMARY KEY (id),	INDEX ID (id),	FULLTEXT INDEX search_index (name, description))");
//
//
//	alter("ALTER TABLE africatranscriptions_images ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_invoiceitems ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_invoiceitemtemplates ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_invoices ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_loginaudit ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_members ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_messages ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_offices ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_pagenavigation ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_pageroles ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_pages ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_province ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_quoteitems ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_quotenumbers ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_quotes ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_roles ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_siteconfig ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_typist ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_typistinvoices ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
	alter("ALTER TABLE africatranscriptions_userroles ADD COLUMN metacreateddate DATETIME NOT NULL, ADD COLUMN metacreateduserid INT NOT NULL AFTER metacreateddate, ADD COLUMN metamodifieddate DATETIME NOT NULL AFTER metacreateduserid, ADD COLUMN metamodifieduserid INT NOT NULL AFTER metamodifieddate;");
?>
